name: LanguageSystem
version: ${project.version}
main: de.glowman554.lang.LanguageSystemMain
api-version: 1.19
author: Glowman554
commands:
  language:
    description: Change your language settings
  reload:
    description: Reload languages
    permission: language.reload